baseURL = "https://crc-trr-270-hommage-z-inf.github.io/Z-INF-Website/"
languageCode = "en"
title = "CRC/TRR 270 HoMMage Z-INF"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  contact_email = "ross.knapman@uni-due.de"
  attribution   = false  # hide "Powered by Lynx" if you prefer

  [params.author]
    name     = "CRC/TRR 270 HoMMage Z-INF Link Hub"
    headline = "This page lists the services of the CRC/TRR 270 HoMMage Z-INF."

    links = [
      { elabftw = { href = "https://sfb270eln.physik.uni-due.de/", text = "eLabFTW" } }
    ]

[module]
  [[module.imports]]
    path = "github.com/jpanther/lynx"
    # version = "v1.6.0"  # pin a specific Lynx release if desired
